#!/usr/bin/env bash
# This script configures an Ubuntu server 
grep -v localhost < /etc/hosts > temp
echo "127.0.0.2 localhost" >> temp
echo "8.8.8.8 facebook.com" >> temp

cat temp > /etc/hosts
rm temp